/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViewerRouteImport } from './routes/viewer'
import { Route as StreamerRouteImport } from './routes/streamer'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChooseRoleRouteImport } from './routes/choose-role'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SLoginRouteImport } from './routes/s/$login'
import { Route as OverlayOverlayTokenRouteImport } from './routes/overlay/$overlayToken'

const ViewerRoute = ViewerRouteImport.update({
  id: '/viewer',
  path: '/viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamerRoute = StreamerRouteImport.update({
  id: '/streamer',
  path: '/streamer',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseRoleRoute = ChooseRoleRouteImport.update({
  id: '/choose-role',
  path: '/choose-role',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SLoginRoute = SLoginRouteImport.update({
  id: '/s/$login',
  path: '/s/$login',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayOverlayTokenRoute = OverlayOverlayTokenRouteImport.update({
  id: '/overlay/$overlayToken',
  path: '/overlay/$overlayToken',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/choose-role': typeof ChooseRoleRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/streamer': typeof StreamerRoute
  '/viewer': typeof ViewerRoute
  '/overlay/$overlayToken': typeof OverlayOverlayTokenRoute
  '/s/$login': typeof SLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/choose-role': typeof ChooseRoleRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/streamer': typeof StreamerRoute
  '/viewer': typeof ViewerRoute
  '/overlay/$overlayToken': typeof OverlayOverlayTokenRoute
  '/s/$login': typeof SLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/choose-role': typeof ChooseRoleRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/streamer': typeof StreamerRoute
  '/viewer': typeof ViewerRoute
  '/overlay/$overlayToken': typeof OverlayOverlayTokenRoute
  '/s/$login': typeof SLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/choose-role'
    | '/dashboard'
    | '/login'
    | '/settings'
    | '/streamer'
    | '/viewer'
    | '/overlay/$overlayToken'
    | '/s/$login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/choose-role'
    | '/dashboard'
    | '/login'
    | '/settings'
    | '/streamer'
    | '/viewer'
    | '/overlay/$overlayToken'
    | '/s/$login'
  id:
    | '__root__'
    | '/'
    | '/choose-role'
    | '/dashboard'
    | '/login'
    | '/settings'
    | '/streamer'
    | '/viewer'
    | '/overlay/$overlayToken'
    | '/s/$login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChooseRoleRoute: typeof ChooseRoleRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  StreamerRoute: typeof StreamerRoute
  ViewerRoute: typeof ViewerRoute
  OverlayOverlayTokenRoute: typeof OverlayOverlayTokenRoute
  SLoginRoute: typeof SLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/viewer': {
      id: '/viewer'
      path: '/viewer'
      fullPath: '/viewer'
      preLoaderRoute: typeof ViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streamer': {
      id: '/streamer'
      path: '/streamer'
      fullPath: '/streamer'
      preLoaderRoute: typeof StreamerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-role': {
      id: '/choose-role'
      path: '/choose-role'
      fullPath: '/choose-role'
      preLoaderRoute: typeof ChooseRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$login': {
      id: '/s/$login'
      path: '/s/$login'
      fullPath: '/s/$login'
      preLoaderRoute: typeof SLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay/$overlayToken': {
      id: '/overlay/$overlayToken'
      path: '/overlay/$overlayToken'
      fullPath: '/overlay/$overlayToken'
      preLoaderRoute: typeof OverlayOverlayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChooseRoleRoute: ChooseRoleRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  StreamerRoute: StreamerRoute,
  ViewerRoute: ViewerRoute,
  OverlayOverlayTokenRoute: OverlayOverlayTokenRoute,
  SLoginRoute: SLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
