export const SUBMIT_RATE_LIMIT_SECONDS = 30;
export const DUPLICATE_WINDOW_SECONDS = 5 * 60;
export const OVERLAY_BACKLOG_LIMIT = 20;
export const OVERLAY_INITIAL_WINDOW_MINUTES = 30;
export const LIVE_CACHE_SECONDS = 75;
export const OVERLAY_DISPLAY_SECONDS = 10;
